<?xml version="1.0" encoding="utf-8"?><Database Name="EMAIL" Class="LINQCLASSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-69AAMS8P\SQLEXPRESS;Initial Catalog=EMAIL;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="EMAIL_System.Properties.Settings" SettingsPropertyName="EMAILConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.email" Member="emails">
    <Type Name="email">
      <Column Name="EmailID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ToWho" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FromWho" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmailTitle" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="EmailText" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.LoginData" Member="LoginDatas">
    <Type Name="LoginData">
      <Column Name="PersonID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Pass" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>